CREATE OR REPLACE DATABASE DEMO_DB;
CREATE OR REPLACE SCHEMA DEMO_SCHEMA;
 

CREATE OR REPLACE NOTIFICATION INTEGRATION ERROR_NOTIFICATION
ENABLED = TRUE
TYPE = QUEUE
NOTIFICATION_PROVIDER = AWS_SNS
DIRECTION = OUTBOUND
AWS_SNS_TOPIC_ARN =''
AWS_SNS_ROLE_ARN = '';

DESC NOTIFICATION INTEGRATION ERROR_NOTIFICATION

  
CREATE OR REPLACE TABLE  EMPLOYEE (
    ID INT,
    Name STRING,
    Age INT,
    City STRING,
    Occupation STRING
);

CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL','null')
  EMPTY_FIELD_AS_NULL = TRUE;


  CREATE OR REPLACE STAGE MY_STAGE 
  URL="S3:"
  CREDENTIALS=(AWS_KEY_ID=''
  AWS_SECRET_KEY='')
  FILE_FORMAT=MY_CSV_FORMAT;
  LIST @MY_STAGE;
 

CREATE OR REPLACE PIPE MY_PIPE
AUTO_INGEST = TRUE
ERROR_INTEGRATION = ERROR_NOTIFICATION
AS 
COPY INTO EMPLOYEE
FROM @MY_STAGE
FILE_FORMAT=(FORMAT_NAME=MY_CSV_FORMAT);
SHOW PIPES;

SELECT * FROM EMPLOYEE;
